// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaFegwdB0SD5NID2GxRD5-s7_0VxiLKO4',
    appId: '1:226949107241:web:a9f19df57373ca75131638',
    messagingSenderId: '226949107241',
    projectId: 'appproject-c5edb',
    authDomain: 'appproject-c5edb.firebaseapp.com',
    storageBucket: 'appproject-c5edb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7wnV6GR2eGKEZppPRlQKw5zVZMNF62E',
    appId: '1:226949107241:android:da434dfbb832b92e131638',
    messagingSenderId: '226949107241',
    projectId: 'appproject-c5edb',
    storageBucket: 'appproject-c5edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADSuDv7dsiYyXTrUyO5NHN7yOgTl710rw',
    appId: '1:226949107241:ios:f5db2ef8d9b4e206131638',
    messagingSenderId: '226949107241',
    projectId: 'appproject-c5edb',
    storageBucket: 'appproject-c5edb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADSuDv7dsiYyXTrUyO5NHN7yOgTl710rw',
    appId: '1:226949107241:ios:f5db2ef8d9b4e206131638',
    messagingSenderId: '226949107241',
    projectId: 'appproject-c5edb',
    storageBucket: 'appproject-c5edb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
